language: python
python:
    - "2.7"

script: make test
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: scotchandrose.com.au
  skip_cleanup: true