language: python
python:
    - "3.5"

script: true
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: scotchandrose.net
  endpoint: scotchandrose.net.s3-website-ap-southeast-2.amazonaws.com
  region: ap-southeast-2
  skip_cleanup: true