language: python
python:
    - "3.5"

script: true
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: http://scotchandrose.com.au.s3-website-ap-southeast-2.amazonaws.com
  skip_cleanup: true